spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://bookms
          predicates:
            - Path=/books/**
          filters:
            - StripPrefix=1
        - id: issue-service
          uri: lb://issuerms
          predicates:
            - Path=/issues/**
          filters:
            - StripPrefix=1