eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  application:
    name: school
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: Root123$
  jpa:
    hibernate:
      ddl-auto: create
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    students-url: http://localhost:8090/api/v1/student

management:
  tracing:
    sampling:
      probability: 1.0