eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jjdbc:mysql://localhost:3306/student
    username: root
    password: Root123$
  jpa:
    hibernate:
      ddl-auto: create
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0